name: Compila Wallet Pass

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codice
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installa dipendenze
        run: npm install passkit-generator node-forge

      - name: Esegui Script di Firma
        env:
          APPLE_PASS_CERT: ${{ secrets.APPLE_PASS_CERT }}
          APPLE_PASS_PASSWORD: ${{ secrets.APPLE_PASS_PASSWORD }}
          APPLE_WWDR_CERT: ${{ secrets.APPLE_WWDR_CERT }}
        run: node index.js

      - name: Verifica firma PKCS#7
        run: |
          rm -rf pass_check
          mkdir pass_check
          unzip -q MioPass.pkpass -d pass_check

          echo "=== CERTIFICATI PRESENTI NELLA FIRMA ==="
          openssl pkcs7 `
            -inform DER `
            -in pass_check/signature `
            -print_certs `
            -noout

          echo "=== VERIFICA CRITTOGRAFICA DELLA FIRMA ==="
          openssl smime `
            -verify `
            -inform DER `
            -in pass_check/signature `
            -content pass_check/manifest.json `
            -noverify `
            -out /dev/null

          echo "=== FIRMA PKCS#7 VERIFICATA ==="

      - name: Salva il file .pkpass scaricabile
        uses: actions/upload-artifact@v4
        with:
          name: pacchetto-pass
          path: MioPass.pkpass

